config/routes.rb
Rails.application.routes.draw do
  
  
  	root "players#pagInicial"
  	get "players/busca" => "players#busca", as: :busca_player

  	resources :players, only: [:new,:create,:destroy,:edit,:update]
	  	# get "/players/new" => "players#new"
	  	# post"/players" => "players#create"
	  	# delete "/players/:id" => "players#destroy", as: :player
	resources :treinamentos
end
	

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord

	validates :nome , length: { minimum: 5} 
	validates :nick , presence: true
	# validates :ranked , presence: true
	validates :email_id, uniqueness: true, format: { with: /\b[A-Z0-9._%a-z\-]+@aluno\.uece\.br\z/,
 	                  message: "deve ser uma conta aluno.uece.br" }

 	belongs_to :treinamento
end

app/models/treinamento.rb
class Treinamento < ApplicationRecord
	has_many :player

	validates :dia , presence: true
	validates :horario , presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController

	def PagInicial
		@fullplayer = Player.all.order :nome 
	end	
	
	def new
		valores = params.require(:player).permit :nome,:nick,:posicao,:ranked,:horario
		@player = Player.new valores
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	before_action :set_player , only: [ :edit , :update ]

	def pagInicial
		@fullplayer = Player.all.order :nome 
		@treinos = Treinamento.all
	end	
	
	def new
		@player = Player.new 
		@treinos = Treinamento.all
	end

	def create 
		@player = Player.new player_params
		
		if@player.save
			flash[:notice] = "Player cadastrado com sucesso"
			redirect_to root_url
		else
			renderiza :new
		end
	end

	def destroy
		id = params[:id]
		Player.destroy id
		redirect_to root_url
	end

	def busca
		@busca_1 = params[:nome]
		@busca_p = Player.where "nome like ?" , "%#{@busca_1}%"
	end

	def edit
		renderiza :edit
	end

	def update
		valores = player_params

		if @player.update valores
			flash[:notice] = "atualizado com sucesso"
			redirect_to root_url
		else
			renderiza :edit
		end	
	end

	private
	def renderiza(view)
		@treinos = Treinamento.all
		render view	
	end

	def set_player
		id = params[:id]
		@player = Player.find(id)
	end

	def player_params
		params.require(:player).permit :nome,:nick,:posicao,:ranked,:treinamento_id,:email_id
	end

end

app/controllers/treinamentos_controller.rb
class TreinamentosController < ApplicationController
  before_action :set_treinamento, only: [:show, :edit, :update, :destroy]

  # GET /treinamentos
  # GET /treinamentos.json
  def index
    @treinamentos = Treinamento.all
  end

  # GET /treinamentos/1
  # GET /treinamentos/1.json
  def show
  end

  # GET /treinamentos/new
  def new
    @treinamento = Treinamento.new
  end

  # GET /treinamentos/1/edit
  def edit
  end

  # POST /treinamentos
  # POST /treinamentos.json
  def create
    @treinamento = Treinamento.new(treinamento_params)

    respond_to do |format|
      if @treinamento.save
        format.html { redirect_to @treinamento, notice: 'Treinamento criado com sucesso' }
        format.json { render :show, status: :created, location: @treinamento }
      else
        format.html { render :new }
        format.json { render json: @treinamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treinamentos/1
  # PATCH/PUT /treinamentos/1.json
  def update
    respond_to do |format|
      if @treinamento.update(treinamento_params)
        format.html { redirect_to @treinamento, notice: 'Treinamento foi atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @treinamento }
      else
        format.html { render :edit }
        format.json { render json: @treinamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treinamentos/1
  # DELETE /treinamentos/1.json
  def destroy
    @treinamento.destroy
    respond_to do |format|
      format.html { redirect_to treinamentos_url, notice: 'Treinamento deletado com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treinamento
      @treinamento = Treinamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def treinamento_params
      params.require(:treinamento).permit(:dia, :horario)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cadastro_helper.rb
module CadastroHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/treinamentos_helper.rb
module TreinamentosHelper
end

app/views/inicio/Cadastrado.html.erb
Cadastrado

app/views/inicio/Cadastro.html.erb
<!-- FORMULÁRIO DE CADASTRO -->
<section id="#d">
  <div class="container-fluid">
    <img src="/images/eSuy3MC.png" alt="Junte-se ao time" id="imagem_form">
	</div>
  <div class="container-fluid">
  
  <!-- <form> -->
  <%= form_for @player do |f| %>

  		<!-- dados do Player -->
  		<div class="form-group row">
    		<label class="col-sm-2 col-form-label">Nome</label>
    		<div class="col-sm-10">
    		 <input type="name" class="form-control" placeholder="Nome" name="player[nome]">
   			</div>
  		</div>
  		<div class="form-group row">
    		<label for="inputEmail3" class="col-sm-2 col-form-label">Email Institucional</label>
    		<div class="col-sm-10">
    	  		<input type="Email" class="form-control" id="inputEmail3" placeholder="exemplo@aluno.uece.br">
    		</div>
  		</div>
		<div class="form-group row">
    		<label for="nick" class="col-sm-2 col-form-label">Nick (L.o.L)</label>
    		<div class="col-sm-10">
    	  		<input type="name" class="form-control" id="nick" placeholder="Nick" name="player[nick]">
    		</div>
  		</div>
  		<div class="form-group row">
    		<label class="col-sm-2 col-form-label">Rank atual</label>
    		<div class="col-sm-10">
    		 	<input type="name" class="form-control" placeholder="Ranked" name="player[ranked]">
   			</div>
  		</div>
  		<div class="form-group row">
    		<label class="col-sm-2 col-form-label">Horários disponíveis para treino</label>
    		<div class="col-sm-10">
    		 <input type="name" class="form-control" placeholder="dia da semana/horário" name="player[horario]">
   			</div>
  		</div>

  	<!-- radios -->
  	<fieldset class="form-group">
    	<div class="row">
      	<legend class="col-form-legend col-sm-2">Posição</legend>
      		<div class="col-sm-10">
        		<div class="form-check">
          			<label class="form-check-label">
            			<input class="form-check-input" type="radio" name="player[posicao:"TOP"]" id="gridRadios1" value="TOP" checked>Top lane
            		</label>
        		</div>
        		<div class="form-check">
          			<label class="form-check-label">
            			<input class="form-check-input" type="radio" name="player[posicao:"JG"]" id="gridRadios2" value="JG">Jungle
            		</label>
  				</div>
  	 			<div class="form-check">
          			<label class="form-check-label">
            			<input class="form-check-input" type="radio" name="player[posicao:"MID"]" id="gridRadios3" value="MID">Mid Lane
            		</label>
  				</div>
	      		<div class="form-check">
          			<label class="form-check-label">
            			<input class="form-check-input" type="radio" name="player[posicao:"SUP"]" id="gridRadios4" value="SUP">Suporte
            		</label>
  				</div>
	        	<div class="form-check">
          			<label class="form-check-label">
            			<input class="form-check-input" type="radio" name="player[posicao:"ADC"]" id="gridRadios5" value="ADC">AD Carry
            		</label>
  				</div>	
	      	</div>
	    </div>
	</fieldset>
		

	<div class="form-group row">
	    <div class="col-sm-10">
	      <div class="form-check">
	        <label class="form-check-label">
	          <input class="form-check-input" type="checkbox"> Receber e-mails informativos. 
	      </label>
	      </div>
	    </div>
	  </div>
	  <div class="form-group row">
	    <div class="col-sm-10">
	      <button type="submit" class="btn btn-dark">Cadastrar</button>
	    </div>
	  </div>
   <% end %>
	<!-- </form> -->
  </div>
</section>

app/views/inicio/PagInicial.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#a">Phantom Black</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#a">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#b">Players</a>
      </li>
      <!--<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>-->
      <li class="nav-item">
        <a class="nav-link" href="#c">Posts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/cadastro">Cadastro</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


<!-- TABELA DE PLAYERS -->
<section id="#c">
	<div class="container-fluid">
		<table class="table table-striped table-dark">
 		<thead>
    		<tr>
    		  	<th scope="col">Phantom</th>
    		  	<th scope="col">Nome</th>
    		  	<th scope="col">Nick</th>
    		  	<th scope="col">Posição</th>
    		  	<th scope="col">Ranked</th>
    		  	<th scope="col">Horários disponíveis</th>
    		</tr>
  		</thead>
  		<tbody>
  	 		<tr>
  	 			<% @fullplayer.each do |player| %>
  	  			<th scope="row">&gt;</th>
  	  		  	<td><%= player.nome%></td>
  	  		  	<td><%=player.nick%></td>
  	  		  	<td><%=player.posicao%></td>
  	  		  	<td><%=player.ranked%></td>
  	  		  	<td><%=player.horario%></td>
  	  		</tr>
  	  		<% end %>
  		</tbody>
		</table>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phantom</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	  <meta charset="UTF-8"/>
	  <meta name="keywords" content="Phantom e-sports,LOL,UECE,Universidade Estadual do Ceará"/>
  </head>

  <body>
    <!-- NAV BAR TEMPLATE -->



    <!-- NAV BAR  -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">


      <a class="navbar-brand" href="http://localhost:3000">Phantom Black</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="http://localhost:3000">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://localhost:3000/#c">Players</a>
          </li>
          <!--<li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>-->
          <li class="nav-item">
            <a class="nav-link" href="#">Posts</a>
          </li>
          <li class="nav-item">
            <%= link_to "Cadastro" , new_player_url , class: "nav-link" %>
            <!-- <a class="nav-link" href="http://localhost:3000/players/new">Cadastro</a> -->
          </li>
        </ul>
          <%= form_tag busca_player_path , method: :get, class: "form-inline my-2 my-lg-0" do %>
            <%= text_field_tag :nome, @busca_1, class: "form-control mr-sm-2" %>
            <%= button_to "Search", nil, class: "btn btn-dark" %>
          <% end %>

        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>-->


      </div>
    </nav>




      <%= yield %><!--rota index.html.erb -->
    <footer id="footer">
    <div class="container-fluid">
      <center id="footer1">Universidade Estadual do Ceará - Phatom Black e-sports. Todos os direitos reservados<br/>
        &copy;  Desenvolvido por <a id="link_to_acens" href="acensjr.com" target="_Blank">Acens</a>
      </center>
    </div>
    </footer>
  </body>
<!-- <script src="/assets/javascripts/code.js"></script>
 -->
</html>

app/views/players/_form.html.erb
<!-- FORMULÁRIO DE CADASTRO -->

<div class="container-fluid">
<section id="#d">

    <!-- mensagem de erro -->
    <% @player.errors.full_messages.each do |message| %>
        <div id="alert_erro" class="alert alert-dark" role="alert">
            <%= message %>
        </div>
    <% end %>

    <h1 id="Cadastro_title">Faça parte do Time</h1>
    <h6 id="Cadastro_title"> * campo obrigatório</h6>
    <img src="/images/eSuy3MC.png" alt="Junte-se ao time" id="imagem_form">

    <!-- Formulário -->
    <%= form_for @player do |f| %>

  		<!-- dados do Player -->
  		<div class="form-group row-center">
    		<label class="col-sm-2 col-form-label">Nome *</label>
    		  <div class="col-sm-10">
    		    <!-- <input type="name" class="form-control" placeholder="Nome" name="player[nome]"> -->
   			    <%= f.text_field :nome, class: "form-control", placeholder:"Nome e Sobrenome" %>
          </div>
  		</div>

      <div class="form-group row-center">
    	<label for="inputEmail3" class="col-sm-2 col-form-label">Email Institucional *</label>
    		  <div class="col-sm-10">
    	  		<%= f.text_field :email_id , class: "form-control" , placeholder: "exemplo@aluno.uece.br"%>
    		  </div>
  		</div>

    <div class="form-group row-center">
    	<label for="nick" class="col-sm-2 col-form-label">Nick *</label>
    		<div class="col-sm-10">
    	  		<!-- <input type="name" class="form-control" id="nick" placeholder="Nick" name="player[nick]"> -->
    		    <%= f.text_field :nick, class: "form-control" , placeholder: "Nick in-game"%>
            </div>
  		</div>

      <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-legend col-sm-2">Ranked</legend>
            <div class="col-sm-4">
                <div class="form-check">
            		<!-- <input type="name" class="form-control" placeholder="Ranked" name="player[ranked]"> -->
           	        <%= f.radio_button :ranked, 'Bronze', :checked => true, class: "form-check-input"%>
                    <%= f.label 'Bronze' , class: "form-check-label"%><br/>

                    <%= f.radio_button :ranked, 'Prata', class: "form-check-input"%>
                    <%= f.label 'Prata' , class: "form-check-label"%><br/>

                    <%= f.radio_button :ranked, 'Ouro', class: "form-check-input"%>
                    <%= f.label 'Ouro' , class: "form-check-label"%><br/>

                    <%= f.radio_button :ranked, 'Platina',class: "form-check-input"%>
                    <%= f.label 'Platina' , class: "form-check-label"%><br/>

                    <%= f.radio_button :ranked, 'Diamante ou +', class: "form-check-input"%>
                    <%= f.label 'Diamante ou Superior' , class: "form-check-label"%><br/>

                </div>
  		    </div>
        </div>
      </fieldset>


      <div class="form-group row-center">
        <%= f.label :treinamento , class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <div class="form-check">
            <%= @treinos.each do |treinamento| %>
              <%= f.radio_button :treinamento_id , @treinos , class: "form-check-input"%>
              <%= f.label :treinamento , treinamento.dia , class: " form-check-label" %><br/>
            <%end%>
          </div>


            <%= f.collection_select :treinamento_id , @treinos, :id, :dia , {} ,
            class: "form-control" %>
        </div>
      </div>

  	<!-- radios -->
  	<fieldset class="form-group">
    	<div class="row">
      	<legend class="col-form-legend col-sm-2">Posição</legend>
      		<div class="col-sm-10">
        		<div class="form-check">

                    <%= f.radio_button :posicao, 'TOP', :checked => true, class: "form-check-input"%>
                    <%= f.label 'Top lane' , class: "form-check-label"%>

                  <!-- <input class="form-check-input" type="radio"
                  name="player[posicao:"TOP"]" id="gridRadios1" value="TOP" checked>Top lane -->

        		</div>
        		<div class="form-check">

            		<%= f.radio_button :posicao, 'JG', class: "form-check-input" %>
                    <%= f.label 'Jungle', class: "form-check-label"%>
                  <!-- <input class="form-check-input" type="radio" name="player[posicao:"JG"]" id="gridRadios2" value="JG">Jungle -->

  				</div>
  	 			<div class="form-check">

                    <%= f.radio_button :posicao, 'MID', class: "form-check-input" %>
                    <%= f.label 'Mid Lane', class: "form-check-label"%>
            			<!-- <input class="form-check-input" type="radio" name="player[posicao:"MID"]" id="gridRadios3" value="MID">Mid Lane -->

  				</div>
	      		<div class="form-check">

          		    <%= f.radio_button :posicao, 'SUP', class: "form-check-input" %>
                    <%= f.label 'Suporte', class: "form-check-label"%>
            			<!-- <input class="form-check-input" type="radio" name="player[posicao:"SUP"]" id="gridRadios4" value="SUP">Suporte -->

  				</div>
	        	<div class="form-check">

          			<%= f.radio_button :posicao, 'ADC', class: "form-check-input" %>
                <%= f.label 'AD Carry', class: "form-check-label"%>
            			<!-- <input class="form-check-input" type="radio" name="player[posicao:"ADC"]" id="gridRadios5" value="ADC">AD Carry -->

  				</div>
	      	</div>
	    </div>
	</fieldset>


	<div class="form-group">
	    <div class="col-sm-4">
	      <div class="form-check">
	        <label class="form-check-label">
	          <input class="form-check-input" type="checkbox"> Receber e-mails informativos.
	      </label>
	      </div>
	    </div>
	  </div>
	  <div class="form-group row-right">
	    <div class="col-sm-4">
	      <!-- <button type="submit" class="btn btn-dark">Cadastrar</button> -->
	     <%= f.submit text_action , class: "btn btn-dark" %>
      </div>
	  </div>
   <% end %>

</section>
</div>

app/views/players/_player.html.erb
<tr>
  	<th id="playerJS" scope="row">&gt;</th>
  	<td id="nomeP"><%= player.nome %></td>
    <td id="nickP"><%= player.nick %></td>
  	<td id="posicaoP"><%= player.posicao %></td>
  	<td id="rankedP"><%= player.ranked %></td>
  	<td id="horarioP"><%= player.treinamento.dia %></td>
    <td><%= button_to "remover" , player , method: :delete, class: "btn btn-danger", data: {confirm: "Confirmar ação delete do player : #{player.nome} - #{player.nick} ?"} %></td>
    <td><%= link_to "editar" , edit_player_path(player) , class: "btn btn-primary" %></td>
</tr>

app/views/players/_tabelatreino.html.erb
	<tr>
  	<!-- <th id="playerJS" scope="row">&gt;</th> -->
	  	<td id="nomeP"><%= player.nome %></td>
	    <td id="nickP"><%= player.nick %></td>
	  	<td id="posicaoP"><%= player.posicao %></td>
	  	<td id="rankedP"><%= player.ranked %></td>
	</tr>

app/views/players/busca.html.erb
<div id="tabela_player">
    <table class="table table-striped table-dark">
 	    <thead>
    		<tr>
    		  	<th scope="col">Phantom</th>
    		  	<th scope="col">Nome</th>
    		  	<th scope="col">Nick</th>
    		  	<th scope="col">Posição</th>
    		  	<th scope="col">Ranked</th>
    		  	<th scope="col">Horários disponíveis</th>
                <th scope="col">Remover</th>
    		</tr>
  		</thead>
        <tbody>
  		    <%= render partial: "player" , collection: @busca_p %>
		</tbody>
    </table>
</div>   

app/views/players/create.html.erb
 <div class="container-fluid">
	<div id="player_criado">
		<h1 id ="cadastrado">
			Cadastrado com Sucesso!
		</h1>
	</div>
</div>

app/views/players/edit.html.erb
<%= render partial: 'form' , locals: {text_action:'Atualizar player'} %>

app/views/players/new.html.erb
<%= render partial: 'form' , locals: { text_action: 'Cadastrar'} %>

app/views/treinamentos/_form.html.erb
<div class="scaffold">

<%= form_with(model: treinamento, local: true) do |form| %>

  <% if treinamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(treinamento.errors.count, "error") %>  - Não foi possível salvar Treino pelos seguintes motivos :</h2>

      <ul>
      <% treinamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dia , class: "col-sm-2 col-form-label" %>
    <%= form.text_field :dia, id: :treinamento_dia , class: "form-treino" %>
  </div>

  <div class="field">
    <%= form.label :horario , class: "col-sm-2 col-form-label"%>
    <%= form.text_field :horario, id: :treinamento_horario , class: "form-treino" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/treinamentos/edit.html.erb
<div class="scaffold">
	<div class="container-fluid">
		<h1>Editing Treinamento</h1>

		<%= render 'form', treinamento: @treinamento %>

		<%= link_to 'Show', @treinamento , class: "btn btn-dark"%> 
		<%= link_to 'Back', treinamentos_path , class: "btn btn-dark"%>
	</div>
</div>

app/views/treinamentos/index.html.erb
<div class="scaffold">
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h1>Treino</h1>

  <table class="treinos">
    <thead>
      <tr>
        <th>Dia</th>
        <th>Horario</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @treinamentos.each do |treinamento| %>
        <tr>
          <td><%= treinamento.dia %></td>
          <td><%= treinamento.horario %></td>
          <td><%= link_to 'Show', treinamento, class: "btn btn-primary" %></td>
          <td><%= link_to 'Edit', edit_treinamento_path(treinamento), class: "btn btn-warning" %></td>
          <td><%= link_to 'Destroy', treinamento, method: :delete, data: { confirm: 'Tem certeza?' } , class: 
          "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Treinamento', new_treinamento_path, class: "btn btn-dark" %>
</div>
</div>

app/views/treinamentos/new.html.erb
<div class="scaffold">
	<div class="container-fluid">
		<h1>New Treinamento</h1>

		<%= render 'form', treinamento: @treinamento %>

		<%= link_to 'Back', treinamentos_path , class: "btn btn-dark" %>
	</div>
</div>

app/views/treinamentos/show.html.erb
<div class="scaffold">
	<div class="container-fluid">
		<p id="alert_erro" class="alert alert-dark" role="alert""><%= notice %></p>

		<p>
		  <strong>Dia:</strong>
		  <%= @treinamento.dia %>
		</p>

		<p>
		  <strong>Horario:</strong>
		  <%= @treinamento.horario %>
		</p>

		<%= link_to 'Edit', edit_treinamento_path(@treinamento), class: "btn btn-dark" %> 
		<%= link_to 'Back', treinamentos_path , class: "btn btn-dark"%>
	</div>
</div>